//Remarks - proof of revisions and to identify the author and details of the class
/*Author: Ralfh Noquera
 * Description: Handler for Account Object
 * History: 
 * 02-07-2023  Initial Release
*/

//Apex Class
//type class apex name
public class UpdateContactHandler {
    
    //Function
    //type static void function name
    //static - you can call this function without instantiating
    //void - does not require a value to return
    public static void sampleFunction() {
        //Declare variable
        //Datatype variable = value
        Integer x = 1 + 1;
        system.debug('Answer:' + x);
    }
    
    //type static datatype functionname
    private static String sampleFunction2() {
        Integer x = 1 + 1;
        String y = 'Sample';
        return y;
    }
}